services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tickets_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    image: newmatheused/ticketsadmin_backend:latest
    restart: always
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DB_USERNAME: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: "${MYSQL_DATABASE}"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - tickets_network

  frontend:
    build: ./frontend
    image: newmatheused/ticketsadmin_frontend:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - tickets_network

volumes:
  db_data:

networks:
  tickets_network:
    driver: overlay
    attachable: true  # Permite que containers individuais se conectem a essa rede