FROM python:3.9-slim
WORKDIR /app

# Instala dependências
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expõe a porta 5000
EXPOSE 5000

# Usa Gunicorn para rodar o app em produção
CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app"]
