FROM python:3.9-slim
WORKDIR /app

# Instala dependências
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia todo o restante do código da aplicação
COPY . .

EXPOSE 5000

CMD ["python", "run.py"]

#CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app", "--workers", "4", "--threads", "2", "--timeout", "120"]